name: leveldb_example
description: Demonstrates how to use the leveldb plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.6.4
  path_provider:

  leveldb:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter

  test: any


flutter:
  uses-material-design: true