include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: 
    - example/**
    - ios/**
    - android/**
    - macos/**
    - test/**

linter:
  rules:
    camel_case_types: false
    invalid_use_of_protected_member: false