name: leveldb
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  ffi: ^0.1.3-dev.3

dev_dependencies:
  flutter_driver:
    sdk: flutter

  test: any
    
  pedantic: ^1.0.0